# config_no_aug.yaml
paths:
  images: "./data/images/"
  masks: "./data/masks/"
  save_model: "./models/unet.pth"
  plot_loss: "./report/figures/loss_curve1.png"
  plot_output: "./report/figures/output1.png"

model:
  feature_channels: 32
  depth: 4
  init_weights: true    # initialize weights with Kaiming Normal

augmentation:
  enabled: false        # disables DualRotation, Flip, Jitter

training:
  run_training: false  #  set to true to run training
  batch_size: 8
  test_batch_size: 1
  learning_rate: 0.001
  epochs: 50
  patience: 3           # lr scheduler patience (ReduceLROnPlateau)
  save_best_val: true   # save best model based on validation loss

reporting:
  plot_title: "U-Net without Augmentation"
